name: flutterpress
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.4.4
  hive_flutter: ^0.3.1

  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  get: ^3.4.6
  after_layout: ^1.0.7+2
  devicelocale: ^0.3.1
  font_awesome_flutter: ^8.8.1

  image_picker: ^0.6.7+7
  permission_handler: ^5.0.1+1
  flutter_image_compress: ^0.7.0
  cached_network_image: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/